workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "MyGameCatalog/MyGameCatalog.xcodeproj"
        XCODE_SCHEME: "MyGameCatalog"
    scripts:
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - yudi.marta.arianto@gmail.com